#!/bin/sh

cd $(dirname $0)

java \
  -server -XX:+UseNUMA -XX:+UseParallelGC \
  -Xms256M -Xmx512M \
  -Djava.awt.headless=true \
  -Djava.net.preferIPv4Stack=true \
  -Djava.net.preferIPv6Addresses=false \
  -classpath "./lib/*:./etc/conf.mssql" \
trade.srv.HttpEndpoint -p 9081
