#!/bin/sh

cd $(dirname $0)

java -Dapp=trade-gendata \
-server \
-Xms32M -Xmx128M \
-Djava.awt.headless=true \
-Djava.net.preferIPv4Stack=true \
-Djava.net.preferIPv6Addresses=false \
-Dfile.encoding=UTF-8 \
-classpath "./lib/*" \
trade.datagen.DataGenerator --input-path=./in --output-path=./out --accounts=5000 --quotes=1000 --holdings=5
