
\copy account_permission FROM '../../data.files/flat_out/AccountPermission.txt' DELIMITER '|'
\copy customer FROM '../../data.files/flat_out/Customer.txt' DELIMITER '|'
\copy customer_account FROM '../../data.files/flat_out/CustomerAccount.txt' DELIMITER '|'
\copy customer_taxrate FROM '../../data.files/flat_out/CustomerTaxrate.txt' DELIMITER '|'
\copy holding FROM '../../data.files/flat_out/Holding.txt' DELIMITER '|'
\copy holding_history FROM '../../data.files/flat_out/HoldingHistory.txt' DELIMITER '|'
\copy holding_summary FROM '../../data.files/flat_out/HoldingSummary.txt' DELIMITER '|'
\copy watch_item FROM '../../data.files/flat_out/WatchItem.txt' DELIMITER '|'
\copy watch_list FROM '../../data.files/flat_out/WatchList.txt' DELIMITER '|'
\copy broker FROM '../../data.files/flat_out/Broker.txt' DELIMITER '|'
\copy cash_transaction FROM '../../data.files/flat_out/CashTransaction.txt' DELIMITER '|'
\copy charge FROM '../../data.files/flat_out/Charge.txt' DELIMITER '|'
\copy commission_rate FROM '../../data.files/flat_out/CommissionRate.txt' DELIMITER '|'
\copy settlement FROM '../../data.files/flat_out/Settlement.txt' DELIMITER '|'
\copy trade FROM '../../data.files/flat_out/Trade.txt' DELIMITER '|'
\copy trade_history FROM '../../data.files/flat_out/TradeHistory.txt' DELIMITER '|'
-- \copy trade_request FROM '../../data.files/flat_out/TradeRequest.txt' DELIMITER '|'
\copy trade_type FROM '../../data.files/flat_out/TradeType.txt' DELIMITER '|'
\copy company FROM '../../data.files/flat_out/Company.txt' DELIMITER '|'
\copy company_competitor FROM '../../data.files/flat_out/CompanyCompetitor.txt' DELIMITER '|'
\copy daily_market FROM '../../data.files/flat_out/DailyMarket.txt' DELIMITER '|'
\copy exchange FROM '../../data.files/flat_out/Exchange.txt' DELIMITER '|'
\copy financial FROM '../../data.files/flat_out/Financial.txt' DELIMITER '|'
\copy industry FROM '../../data.files/flat_out/Industry.txt' DELIMITER '|'
\copy last_trade FROM '../../data.files/flat_out/LastTrade.txt' DELIMITER '|'
\copy news_item FROM '../../data.files/flat_out/NewsItem.txt' DELIMITER '|'
\copy news_xref FROM '../../data.files/flat_out/NewsXRef.txt' DELIMITER '|'
\copy sector FROM '../../data.files/flat_out/Sector.txt' DELIMITER '|'
\copy security FROM '../../data.files/flat_out/Security.txt' DELIMITER '|'
\copy address FROM '../../data.files/flat_out/Address.txt' DELIMITER '|'
\copy status_type FROM '../../data.files/flat_out/StatusType.txt' DELIMITER '|'
\copy taxrate FROM '../../data.files/flat_out/Taxrate.txt' DELIMITER '|'
\copy zip_code FROM '../../data.files/flat_out/ZipCode.txt' DELIMITER '|'

