ALTER TABLE account_permission ADD CONSTRAINT pk_account_permission PRIMARY KEY (ap_ca_id, ap_tax_id);
ALTER TABLE customer ADD CONSTRAINT pk_customer PRIMARY KEY (c_id);
ALTER TABLE customer_account ADD CONSTRAINT pk_customer_account PRIMARY KEY (ca_id);
ALTER TABLE customer_taxrate ADD CONSTRAINT pk_customer_taxrate PRIMARY KEY (cx_c_id, cx_tx_id);
ALTER TABLE holding ADD CONSTRAINT pk_holding PRIMARY KEY (h_t_id);
ALTER TABLE holding_history ADD CONSTRAINT pk_holding_history PRIMARY KEY (hh_t_id, hh_h_t_id);
ALTER TABLE holding_summary ADD CONSTRAINT pk_holding_summary PRIMARY KEY (hs_ca_id, hs_s_symb);
ALTER TABLE watch_item ADD CONSTRAINT pk_watch_item PRIMARY KEY (wi_wl_id, wi_s_symb);
ALTER TABLE watch_list ADD CONSTRAINT pk_watch_list PRIMARY KEY (wl_id);
ALTER TABLE broker ADD CONSTRAINT pk_broker PRIMARY KEY (b_id);
ALTER TABLE cash_transaction ADD CONSTRAINT pk_cash_transaction PRIMARY KEY (ct_t_id);
ALTER TABLE charge ADD CONSTRAINT pk_charge PRIMARY KEY (ch_tt_id, ch_c_tier);
ALTER TABLE commission_rate ADD CONSTRAINT pk_commission_rate PRIMARY KEY (cr_c_tier, cr_tt_id, cr_ex_id, cr_from_qty);
ALTER TABLE settlement ADD CONSTRAINT pk_settlement PRIMARY KEY (se_t_id);
ALTER TABLE trade ADD CONSTRAINT pk_trade PRIMARY KEY (t_id);
ALTER TABLE trade_history ADD CONSTRAINT pk_trade_history PRIMARY KEY (th_t_id, th_st_id);
ALTER TABLE trade_request ADD CONSTRAINT pk_trade_request PRIMARY KEY (tr_t_id);
ALTER TABLE trade_type ADD CONSTRAINT pk_trade_type PRIMARY KEY (tt_id);
ALTER TABLE company ADD CONSTRAINT pk_company PRIMARY KEY (co_id);
ALTER TABLE company_competitor ADD CONSTRAINT pk_company_competitor PRIMARY KEY (cp_co_id, cp_comp_co_id, cp_in_id);
ALTER TABLE daily_market ADD CONSTRAINT pk_daily_market PRIMARY KEY (dm_s_symb, dm_date);
ALTER TABLE exchange ADD CONSTRAINT pk_exchange PRIMARY KEY (ex_id);
ALTER TABLE financial ADD CONSTRAINT pk_financial PRIMARY KEY (fi_co_id, fi_year, fi_qtr);
ALTER TABLE industry ADD CONSTRAINT pk_industry PRIMARY KEY (in_id);
ALTER TABLE last_trade ADD CONSTRAINT pk_last_trade PRIMARY KEY (lt_s_symb);
ALTER TABLE news_item ADD CONSTRAINT pk_news_item PRIMARY KEY (ni_id);
ALTER TABLE news_xref ADD CONSTRAINT pk_news_xref PRIMARY KEY (nx_co_id, nx_ni_id);
ALTER TABLE sector ADD CONSTRAINT pk_sector PRIMARY KEY (sc_id);
ALTER TABLE security ADD CONSTRAINT pk_security PRIMARY KEY (s_symb);
ALTER TABLE address ADD CONSTRAINT pk_address PRIMARY KEY (ad_id);
ALTER TABLE status_type ADD CONSTRAINT pk_status_type PRIMARY KEY (st_id);
ALTER TABLE taxrate ADD CONSTRAINT pk_taxrate PRIMARY KEY (tx_id);
ALTER TABLE zip_code ADD CONSTRAINT pk_zip_code PRIMARY KEY (zc_code);
