USE tpce;


SET ANSI_NULLS ON;
SET ANSI_NULL_DFLT_OFF ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;


UPDATE STATISTICS account_permission;
UPDATE STATISTICS customer;
UPDATE STATISTICS customer_account;
UPDATE STATISTICS customer_taxrate;
UPDATE STATISTICS holding;
UPDATE STATISTICS holding_history;
UPDATE STATISTICS holding_summary;
UPDATE STATISTICS watch_item;
UPDATE STATISTICS watch_list;
UPDATE STATISTICS broker;
UPDATE STATISTICS cash_transaction;
UPDATE STATISTICS charge;
UPDATE STATISTICS commission_rate;
UPDATE STATISTICS settlement;
UPDATE STATISTICS trade;
UPDATE STATISTICS trade_history;
UPDATE STATISTICS trade_request;
UPDATE STATISTICS trade_type;
UPDATE STATISTICS company;
UPDATE STATISTICS company_competitor;
UPDATE STATISTICS daily_market;
UPDATE STATISTICS exchange;
UPDATE STATISTICS financial;
UPDATE STATISTICS industry;
UPDATE STATISTICS last_trade;
UPDATE STATISTICS news_item;
UPDATE STATISTICS news_xref;
UPDATE STATISTICS sector;
UPDATE STATISTICS security;
UPDATE STATISTICS address;
UPDATE STATISTICS status_type;
UPDATE STATISTICS taxrate;
UPDATE STATISTICS zip_code;
