#!/bin/sh

cd $(dirname $0)

wd=$(pwd)

exec setuidgid nobody /opt/sapojvm/bin/java -Dapp=twitter.stream.publisher -server \
-Xverify:none -Xms16M -Xmx128M \
-Djava.awt.headless=true \
-Djava.net.preferIPv4Stack=true \
-Djava.net.preferIPv6Addresses=false \
-Dfile.encoding=UTF-8 \
-cp "./conf:./lib/*:./bin" \
org.caudexorigo.twitter.social.Main -h localhost -p 3323  -n /social/portugal/twitter
