ALTER TABLE account ADD CONSTRAINT fk_a1 FOREIGN KEY (profile_userid) REFERENCES accountprofile (userid) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE holding ADD CONSTRAINT fk_h1 FOREIGN KEY (account_accountid) REFERENCES account (accountid) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE holding ADD CONSTRAINT fk_h2 FOREIGN KEY (quote_symbol) REFERENCES quote (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE orders ADD CONSTRAINT fk_o1 FOREIGN KEY (quote_symbol) REFERENCES quote (symbol) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE orders ADD CONSTRAINT fk_o2 FOREIGN KEY (account_accountid) REFERENCES account (accountid) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE orders ADD CONSTRAINT fk_o3 FOREIGN KEY (holding_holdingid) REFERENCES holding (holdingid) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;
