#!/bin/sh

cd $(dirname $0)

pwd=$(pwd)

java -server \
-Xverify:none -Xms16M -Xmx64M -XX:+UseNUMA -XX:+UseParallelGC \
-Djava.awt.headless=true \
-Djava.net.preferIPv4Stack=true \
-Djava.net.preferIPv6Addresses=false \
-Dfile.encoding=UTF-8 \
-cp "./conf:./bin:./lib/*" \
io.netty.example.http.helloworld.HttpHelloWorldServer
