#!/bin/sh

cd $(dirname $0)

wd=$(pwd)

java -server \
-Xverify:none -Xms16M -Xmx128M \
-Djava.awt.headless=true \
-Djava.net.preferIPv4Stack=true \
-Djava.net.preferIPv6Addresses=false \
-Dfile.encoding=UTF-8 \
-cp "./conf:./lib/*:./bin" \
pt.sapo.websocket.labs.Main --port 8081 --root-directory "$wd/wwwroot"
